library(foreign)
data <- read.csv2("household_power_consumption.txt", header = TRUE, na.strings="?")
head(data)
data$DateTime <- strptime(paste0(data$Date,' ',data$Time), '%d/%m/%Y %H:%M:%OS')
datareduced <- data[format(data$DateTime, "%Y%m%d") == '20070201' | format(data$DateTime, "%Y%m%d") == '20070202',]
datareduced$Sub_metering_1 <- as.numeric(datareduced$Sub_metering_1)
datareduced$Sub_metering_2 <- as.numeric(datareduced$Sub_metering_2)
datareduced$Sub_metering_3 <- as.numeric(datareduced$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(x = datareduced$DateTime, y = datareduced$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(datareduced$DateTime, datareduced$Sub_metering_2, type = "l", col = "red")
lines(datareduced$DateTime, datareduced$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=1, col=c("black", "red", "blue"))
dev.off()