library(foreign)
data <- read.csv2("household_power_consumption.txt", header = TRUE, na.strings="?")
head(data)
data$DateTime <- strptime(paste0(data$Date,' ',data$Time), '%d/%m/%Y %H:%M:%OS')
datareduced <- data[format(data$DateTime, "%Y%m%d") == '20070201' | format(data$DateTime, "%Y%m%d") == '20070202',]
datareduced$Sub_metering_1 <- as.numeric(datareduced$Sub_metering_1)
datareduced$Sub_metering_2 <- as.numeric(datareduced$Sub_metering_2)
datareduced$Sub_metering_3 <- as.numeric(datareduced$Sub_metering_3)
datareduced$Voltage <- as.numeric(datareduced$Voltage)
datareduced$Global_reactive_power <- as.numeric(datareduced$Global_reactive_power)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2), mar=c(5,3,3,3))
plot(datareduced$DateTime,datareduced$Global_active_power,type="l",xlab="", ylab="Global Active Power (kilowatts)")
plot(datareduced$DateTime,datareduced$Voltage,type="l",xlab="datetime", ylab="Voltage")
plot(x = datareduced$DateTime, y = datareduced$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(datareduced$DateTime, datareduced$Sub_metering_2, type = "l", col = "red")
lines(datareduced$DateTime, datareduced$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=1, col=c("black", "red", "blue"), bty ='n')
plot(datareduced$DateTime, datareduced$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()